138 add api endpoint for getting his own black card current one
sopra-fs22-group-07/server pull request #142
Opened 2022-04-29 14:49 UTC by daveking7

2022-04-30 13:25 UTC, TwoDigitsOneNumber commented on src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
> +    @GetMapping("/users/{userId}/blackCard")
i know in our application we only get at most 1 card, but i think we should still call it "blackCards" (as we did in the rest interface) to adhere to the standards mentioned in software engineering. What do you think? I'm fine to keep it in singular, but then we should adapt the rest interface, to reflect the design decision

2022-04-30 13:32 UTC, TwoDigitsOneNumber commented on src/test/java/ch/uzh/ifi/hase/soprafs22/controller/GameControllerTest.java
> +import ch.uzh.ifi.hase.soprafs22.entity.WhiteCard;
good practice!

2022-04-30 13:38 UTC, TwoDigitsOneNumber requested changes
tests look good but api endpoint varies from rest interface. a design decision needs to be made

2022-04-30 13:38 UTC, TwoDigitsOneNumber commented on src/main/java/ch/uzh/ifi/hase/soprafs22/controller/GameController.java
> +    @GetMapping("/users/{userId}/blackCard")
i know in our application we only get at most 1 card, but i think we should still call it "blackCards" (as we did in the rest interface) to adhere to the standards mentioned in software engineering. What do you think? I'm fine to keep it in singular, but then we should adapt the rest interface, to reflect the design decision.
Also: the api endpoint path is called users/{userId}/games/blackCards in the interface. I think we should keep the "/game" directory in there

2022-04-30 13:38 UTC, TwoDigitsOneNumber commented on src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
> +   * @param wobject
is this a typo?

2022-05-01 07:25 UTC, daveking7 commented on src/test/java/ch/uzh/ifi/hase/soprafs22/controller/GameControllerTest.java
> +import ch.uzh.ifi.hase.soprafs22.entity.WhiteCard;
Props to my IDE

2022-05-01 07:30 UTC, daveking7 commented on src/test/java/ch/uzh/ifi/hase/soprafs22/controller/UserControllerTest.java
> +   * @param wobject
jup

2022-05-01 07:42 UTC, JoMuelle approved these changes
Looks good

2022-05-01 07:49 UTC, merged